#!/bin/sh
# note that the shebang in the first line is necessary even for windows! 
echo "pre commit"
# stash any unstaged changes
git stash -q --keep-index

# run the tests with Maven
cd TinyME
mvn clean install

# store the last exit code in a variable
RESULT=$?

# return to the root directory
cd ..

# unstash the unstashed changes
git stash pop -q

# print a message
echo "pre commit done"
echo "the result is $RESULT"

# return the 'mvn clean install' exit code
exit $RESULT
